title: Martin RAYNOV's Website
email: mraynov@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Martin RAYNOV's website and blog.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
github_username:  martinraynov

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
