title: Martin RAYNOV's Website
email: mraynov@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Martin RAYNOV's website and blog.
permalink: ':title/'
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
site-twitter: #if your site has a twitter account, enter it here

# Author Settings
author: Martin RAYNOV # add your name
author-img: raynov.jpg
about-author: I am a web developer focusing on front-end development. Always hungry to keep learning. # add description
social-github: martinraynov
social-linkedin: martinraynov
social-email: mraynov@gmail.com

# Disqus
discus-identifier: mr-brown # add your discus identifier

# Tracker
analytics: # Google Analytics

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
